import pyautogui as pg
import time as t
n1 = input("n1")
id1 = input("id1")
h1 = input('h1')

n2 = input("n2")
id2 = input("id2")
h2 = input('h2')

n3 = input("n3")
id3 = input("id3")
h3 = input('h3')

n4 = input("n4")
id4 = input("id4")
h4 = input('h4')

n5 = input("n5")
id5 = input("id5")
h5 = input('h5')

t.sleep(5)

pg.typewrite("<div class='card'>")
pg.press("ENTER")
pg.typewrite("<img src='Images/Profile_pic.webp' alt='StudentImage'>")
pg.press("ENTER")
pg.typewrite("<h4>Student</h4>")
pg.press("ENTER")
pg.typewrite("<p>Name  : "+ n1 + "</p>")
pg.press("ENTER")
pg.typewrite("<p>ID  : 0119 "+ id1 +"</p>")
pg.press("ENTER")
pg.typewrite("<p>House  : " + h1 + "</p>")
pg.press('enter')
pg.press("Backspace")
pg.typewrite("</div>")

pg.press("ENTER")

pg.typewrite("<div class='card'>")
pg.press("ENTER")
pg.typewrite("<img src='Images/Profile_pic.webp' alt='StudentImage'>")
pg.press("ENTER")
pg.typewrite("<h4>Student</h4>")
pg.press("ENTER")
pg.typewrite("<p>Name  : "+ n2 + "</p>")
pg.press("ENTER")
pg.typewrite("<p>ID  : 0119 "+ id2 +"</p>")
pg.press("ENTER")
pg.typewrite("<p>House  : " + h2 + "</p>")
pg.press('enter')
pg.press("Backspace")
pg.typewrite("</div>")

pg.press("ENTER")

pg.typewrite("<div class='card'>")
pg.press("ENTER")
pg.typewrite("<img src='Images/Profile_pic.webp' alt='StudentImage'>")
pg.press("ENTER")
pg.typewrite("<h4>Student</h4>")
pg.press("ENTER")
pg.typewrite("<p>Name  : "+ n3 + "</p>")
pg.press("ENTER")
pg.typewrite("<p>ID  : 0119 "+ id3 +"</p>")
pg.press("ENTER")
pg.typewrite("<p>House  : " + h3 + "</p>")
pg.press('enter')
pg.press("Backspace")
pg.typewrite("</div>")

pg.press("ENTER")

pg.typewrite("<div class='card'>")
pg.press("ENTER")
pg.typewrite("<img src='Images/Profile_pic.webp' alt='StudentImage'>")
pg.press("ENTER")
pg.typewrite("<h4>Student</h4>")
pg.press("ENTER")
pg.typewrite("<p>Name  : "+ n4 + "</p>")
pg.press("ENTER")
pg.typewrite("<p>ID  : 0119 "+ id4 +"</p>")
pg.press("ENTER")
pg.typewrite("<p>House  : " + h4 + "</p>")
pg.press('enter')
pg.press("Backspace")
pg.typewrite("</div>")

pg.press("ENTER")

pg.typewrite("<div class='card'>")
pg.press("ENTER")
pg.typewrite("<img src='Images/Profile_pic.webp' alt='StudentImage'>")
pg.press("ENTER")
pg.typewrite("<h4>Student</h4>")
pg.press("ENTER")
pg.typewrite("<p>Name  : "+ n5 + "</p>")
pg.press("ENTER")
pg.typewrite("<p>ID  : 0119 "+ id5 +"</p>")
pg.press("ENTER")
pg.typewrite("<p>House  : " + h5 + "</p>")
pg.press('enter')
pg.press("Backspace")
pg.typewrite("</div>")


